sudo: false
dist: trusty
language: elixir
elixir:
  - 1.3.3
  - 1.4.5
  - 1.5.3
  - 1.6.1
services:
  - elasticsearch
before_script:
  - 'echo "path.repo: /tmp" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - 'sudo service elasticsearch restart'
  - mix credo --strict
script: "mix test"
notifications:
  email: werbitzky@gmail.com
