sudo: false
dist: trusty
language: elixir
elixir:
  - 1.3.3
services:
  - elasticsearch
before_script:
  - 'echo "path.repo /tmp" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - 'sudo service elasticsearch restart'
script: "mix test"
notifications:
  email: werbitzky@gmail.com
